<h2 class="text-info">Sign In</h2>

<?php echo $this->tag->form("login"); ?>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>
    <p>
        <?php echo $this->tag->checkField("remember"); ?>
        <label for="remember">Remember me</label>
    </p>
    <p>
        <?php echo $this->tag->submitButton(["Login",'class'=>'btn btn-info']); ?>
    </p>
</form>
<p><?php echo $this->response->getContent() ?></p>