<h2 class="text-info">Sign up using this form</h2>

<?php echo $this->tag->form(''); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->emailField("email"); ?>
    </p>
    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>
<div class="alert alert-danger"><?php if (isset($message))echo $message ?></div>